sylius_grid:
    grids:
        app_admin_subscription:
            driver:
                options:
                    class: "%bitbag_sylius_shipping_subscription_plugin.model.shipping_subscription.class%"
            fields:
                customer:
                    type: string
                    label: sylius.ui.customer
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template:
                            "@BitBagSyliusShippingSubscriptionPlugin/Grid/enabled.html.twig"
                order_item_unit.order_item.product_name:
                    type: string
                    label: sylius.ui.product
                created_at:
                    type: datetime
                    label: sylius.ui.from
                end_at:
                    type: datetime
                    label: bitbag_sylius_shipping_subscription_plugin.ui.end_at
            actions:
                item:
                    delete:
                        type: delete
