sylius_grid:
  grids:
    app_admin_subscription:
      driver:
        options:
          class: "%app.model.shipping_subscription.class%"
      fields:
        customer:
          type: string
          label: sylius.ui.customer
        enabled:
          type: twig
          label: sylius.ui.enabled
          options:
            template:
              "@BitBagSyliusShippingSubscriptionPlugin/Grid/enabled.html.twig"
        created_at:
          type: datetime
          label: sylius.ui.from
      actions:
        item:
          delete:
            type: delete