app_subscription:
    resource: |
        alias: bitbag_sylius_shipping_subscription_plugin.shipping_subscription
        section: admin
        templates: '@SyliusAdmin/Crud'
        except: ['show']
        grid: app_admin_subscription
    type: sylius.resource
    prefix: /admin
