winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                bitbag_shipping_subscription_enable:
                    on: ["pay"]
                    do: ["@setono_sylius_gift_card.operator.order_gift_card", "enable"]
                    args: ["object"]
