winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                bitbag_shipping_subscription_enable:
                    on: ["pay"]
                    do: ["@bitbag_sylius_shipping_subscription.operator.shipping_subscription", "enable"]
                    args: ["object"]
